#!/bin/sh
if [ -z "$MONIMI_HOME" ]; then
    export MONIMI_HOME=/home/monimi/monimi
fi

if [ -z "$LIGHTTPD" ]; then
    LIGHTTPD=/opt/lighttpd
fi

if test x$UID = x0; then
  export USER=root
fi

cd $MONIMI_HOME

exec $LIGHTTPD/sbin/lighttpd -D -f etc/lighthttpd.conf
